### ISSUE TITLE
rowspanx prints overlapping cell

### ISSUE THREAD

**Issue by mangkoran** [PgBiel/typst-tablex#105]
When I tried to use nested colspanx and rowspanx, it seems "ONE" is stacked in place, which is not what I expect.

![image](https://github.com/PgBiel/typst-tablex/assets/57625126/1b04ae72-4771-4298-bfae-47be7c1f9b79)

```typst
#tablex(
  columns: (auto, auto, auto, auto),
  colspanx(4, rowspanx(3)[ONE]),
  [TWO], [THREE], [FOUR], [FIVE],
)
```

_Originally posted by @PgBiel in https://github.com/PgBiel/typst-tablex/discussions/104#discussioncomment-7983522_

tablex 0.0.7
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1702233742

**Comment by PgBiel** [comment]
Related: #82

**Comment by PgBiel** [comment]
MRE:

```
#import "@preview/tablex:0.0.7": tablex, cellx, colspanx, rowspanx

a

#tablex(
  columns: 3,
  colspanx(3, rowspanx(2)[a])
)

b
```

produces

![overlap between the table and the following paragraph](https://github.com/PgBiel/typst-tablex/assets/9021226/f7b541ed-06f9-4b95-baec-395566917cc9)

**Comment by PgBiel** [comment]
Seems to be a renderer-specific bug, as it renders fine in the experimental CeTZ renderer.

![image](https://github.com/PgBiel/typst-tablex/assets/9021226/a6f3a560-3f05-441f-a856-83a915c99db9)

**Comment by PgBiel** [comment]
The bug will be fixed in the next release. Thanks!

**Comment by PgBiel** [comment]
In the meantime, you can use `tablex.typ` from the [`0.0.x` branch](https://github.com/PgBiel/typst-tablex/tree/0.0.x) - just download the file, place it in your project and import it.

**Comment by mangkoran** [comment]
Thank you very much! I will just wait for next release as I can work around it 😁

Also CeTZ renderer looks cool 👀
