### ISSUE TITLE
Redundant blanks were generated with `rowspanx`

### ISSUE THREAD

**Issue by rinmyo** [PgBiel/typst-tablex#11]
```typst
tablex(
      columns: (auto, 1fr),
      rowspanx(2, [a\ a\ a\ a\ a]), "dfjasdfjdaskfjdsaklfj", "ddd"
    )
```

![image](https://github.com/PgBiel/typst-tablex/assets/16162768/915c2383-169d-4197-aad4-e3058135fc7e)

**Comment by PgBiel** [comment]
Fixed in 2e5f06c43d87e81b3b04c51a2254f9dca44d696d (will be out in the next release), thanks!
