### ISSUE TITLE
Broken example

### ISSUE THREAD

**Issue by sitandr** [PgBiel/typst-tablex#112]
Hello, just want to notify that one of repository examples is currently broken. I noticed that when adding your package to Typst Examples Book. 

The one with summing columns and `gridx` uses `calc.mod` that has been recently removed. That's not something important, I think almost everyone is able to fix the error themselves, but still.

**Comment by PgBiel** [comment]
Hey, thanks for mentioning. Do you mind opening a PR to fix this?

**Comment by sitandr** [comment]
I'm terribly sorry for the mistake. Actually, on this repository it was already fixed via 155f11639e243fdefe8dc9a6f7b417215ddc677e, I was looking at the old version in packages repository. Closing as completed, sorry again for confusion.

**Comment by PgBiel** [comment]
It's perfectly fine, thanks for reporting!
