### ISSUE TITLE
Colspan + rowspan documentation is wrong?

### ISSUE THREAD

**Issue by wlupton** [PgBiel/typst-tablex#119]
The documentation says to use `colspanx(2)(rowspanx(2)[d])` to set colspan and rowspan at the same time.

Is this a typo? The following gives a `Missing argument: content` error.

```
#tablex(
  columns: 3,
  [a], [b], [c],
  colspanx(2)(rowspanx(2)[d])
)
```

Should it say `colspanx(2, rowspanx(2)[d])`? This works.

```
#tablex(
  columns: 3,
  [a], [b], [c],
  colspanx(2, rowspanx(2)[d])
)
```

**Comment by PgBiel** [comment]
Yep, it was a typo. Will now be fixed in the next release's README. Thanks!
