### ISSUE TITLE
Slight white line shown between cells without vlines specified

### ISSUE THREAD

**Issue by ntjess** [PgBiel/typst-tablex#120]
With `auto-vlines: false`, there's a small white gap showing between cells in svg and pdf formats:

![image](https://github.com/PgBiel/typst-tablex/assets/23620506/fae84a39-b49a-4d7a-99b5-69865509f6db)

Is there a solution other than passing `vlines` that match cell fills?

**Comment by PgBiel** [comment]
Hello, I'm failing to reproduce this with the following setup:

```typ
#import "@preview/tablex:0.0.8": tablex
#table(fill: red, stroke: none, columns: 2)[a][b]
#tablex(fill: red, stroke: none, columns: 2)[a][b]

#tablex(fill: red, auto-vlines: false, columns: 2)[a][b]
```

This sounds like it's something specific to each PDF reader, and so it's likely not something we can solve. However, do you have a sample document I could test this with?

**Comment by ntjess** [comment]
![image](https://github.com/PgBiel/typst-tablex/assets/23620506/1cfa43cb-4181-4c67-bf0a-fb7bfccacdc2)
Oh interesting, your MWE PDF shows the effects on sumatra and the vscode live preview, but not in chrome.
The MWE as an SVG shows the effects in chrome as well. For the record, I tested on 1920x1080 and 1920x1280 displays.

Feel free to close the issue if indeed this is application-specific

**Comment by ntjess** [comment]
I think this isn't localized to typst. I tried with an M$ Word PDF and see the same problems. But the line is quite a bit smaller and only appears at some zoom levels
![image](https://github.com/PgBiel/typst-tablex/assets/23620506/ed824185-f068-4bde-a625-e6e7e57d4907)

**Comment by PgBiel** [comment]
Yeah I guess there isn't much we can do then... I think I'll close this issue for now, but if we have any further insights in the future, we can reopen it. Thanks!
