### ISSUE TITLE
Dual-license as MIT/Apache

### ISSUE THREAD

**Issue by PgBiel** [PgBiel/typst-tablex#134]
For the next release (0.1.0), I'm planning on dual-licensing tablex under MIT and Apache-2.0 (currently just MIT).

For this, I've identified that the only external contribution to the code was by @dixslyf.

@dixslyf do you consent to license your code under Apache-2.0 as well, besides MIT? :slightly_smiling_face:

**Comment by dixslyf** [comment]
Sure, fine by me.

**Comment by PgBiel** [comment]
Thank you!
