### ISSUE TITLE
Hlines not drawn with `gutter-restrict: top`

### ISSUE THREAD

**Issue by dmorawetz** [PgBiel/typst-tablex#20]
I use this package for all my tables to replicate the booktabs style, and it is wonderful to use.

However, with the latest version of tablex and typst, the following code, does not show the hline.

```typst
#import "tablex.typ": tablex, hlinex

#tablex(
  columns: 3,
  row-gutter: 1em,
  auto-lines: false,
  [H1], [H2], [H3],
  hlinex(gutter-restrict: top),
  [seconde], [row], [with content]
)
```
![image](https://github.com/PgBiel/typst-tablex/assets/9783620/d0f13714-9288-4d57-82ad-df43610ec12a)

But `gutter-restrict: bottom` works as expected.

![image](https://github.com/PgBiel/typst-tablex/assets/9783620/3dce2be4-51dd-4583-855a-27161db0a39a)

What can I do to fix this? Plus, is there maybe an option to draw it right in the center of the gutter?

For now, I use `bottom` everywhere, but it is way more visually pleasing if it is aligned right. Please help my OCD :)

**Comment by PgBiel** [comment]
Fixed in 7029956f6cc4fe6659b1066f8cea4c447b4c67bc, thanks!

There are still some other minor gutter issues I wish to fix before the next release, but you can use the code from that commit (or from `main`) in the meantime.

**Comment by PgBiel** [comment]
> is there maybe an option to draw it right in the center of the gutter?

Not currently; please open a separate issue suggesting this :)

**Comment by dmorawetz** [comment]
Wow, thanks for this fast fix! It works :D

Top looks pretty slick, I think the center option is not necessary, now.
