### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by ondohotola** [PgBiel/typst-tablex#25]
I'd like to see if I need to upgrade (manually) so a version number inside would be helpful.

**Comment by PgBiel** [comment]
Sure! Sorry for the inconvenience.

For the time being, try to Ctrl-F search `hline.gutter-restrict != top` in the `tablex.typ` file; if no matches are found, then your current version is not 0.0.4.

**Comment by PgBiel** [comment]
I've added v0.0.4 as a version number in 9da02caff045c73a6a85a2973066618648759836, but I'll keep this issue open so I keep this in mind for the next update (likely v0.0.5).

**Comment by PgBiel** [comment]
Closing this as the version number for v0.0.5 was correctly added to the source file now. Thanks for the suggestion!
