### ISSUE TITLE
tablex inside tablex results issues of following tablex

### ISSUE THREAD

**Issue by yomannnn** [PgBiel/typst-tablex#28]
Hi, 
btw: thank you for the marvellous library!
I observed a strange behaviour: tablex inside tablex results in spacing (column width) issues of following tablex.
See example below .... 
Many thanks ... 

```
// tested with typst-tablex (v0.0.4)
#let mycell = [
  #tablex(
    columns: (1fr, 1fr),
    [A],[A]
  )
]

= table inside a table
#tablex(
  columns: (1fr, 1fr),
  mycell, mycell
)

= following table fails
*Problem/Observation*:  just one column "C"

*Expected Outcome*: Two columns

#tablex(
  columns: (1fr, 1fr),
  [C],[C]
)
```

**Comment by PgBiel** [comment]
Interesting. This doesn't seem to happen when the columns of the last tablex call aren't 1fr. As you present it, however, the last table has zero-sized columns.
I'll investigate it when I can. Thanks for reporting!

**Comment by PgBiel** [comment]
Hi, I've pushed a fix to main in https://github.com/PgBiel/typst-tablex/commit/f00b91c7d9383ebd194fb9e36ee5999339c38891. Can you test and see if it's working properly now? (I'll mark this issue as solved soon, as my own tests seem to indicate this was fixed). Thanks!

**Comment by yomannnn** [comment]
Hi,  I did a quick test and the issue seems to be solved.
I will continue to do some tests and feedback if I detect the issue again.
Many thanks for your support!
