### ISSUE TITLE
Repeated footer rows

### ISSUE THREAD

**Issue by exqmjmz** [PgBiel/typst-tablex#31]
Now implements repeat header rows.
How to implement repeat footer rows?
Here is a screenshot of my document:

![image](https://github.com/PgBiel/typst-tablex/assets/12406935/228fc610-0510-4056-bdb3-038e6c65c926)

**Comment by PgBiel** [comment]
This isn't currently possible, but it's a planned feature. Thanks for opening the issue!

**Comment by PgBiel** [comment]
Since footers were implemented in native tables, I'll close this.
