### ISSUE TITLE
Is there a limit of three nested tables?

### ISSUE THREAD

**Issue by wlupton** [PgBiel/typst-tablex#41]
Is this expected? When the problem occurs, I believe that it can affect other tables in the document.

<img width="540" alt="Screenshot 2023-08-09 at 14 58 43" src="https://github.com/PgBiel/typst-tablex/assets/8874729/531e77ef-6405-48a3-8210-393dc324de0e">

```
Triple-nested tables are fine.

#tablex(
  tablex(
    tablex(
      lorem(10) 
    )
  )
)

Quadruple-nested tables don't seem to wrap correctly.

#tablex(
  tablex(
    tablex(
      tablex(
        lorem(20) 
      )
    )
  )
)
```

**Comment by PgBiel** [comment]
I wouldn't say this is expected, but nested tables seem to be kinda glitchy in general atm. This might improve in the upcoming v0.1.0, not sure to which extent though. Hopefully this is figured out sooner or later. Thanks for the report!

**Comment by PgBiel** [comment]
Hi, I've pushed a fix to main with https://github.com/PgBiel/typst-tablex/commit/f00b91c7d9383ebd194fb9e36ee5999339c38891. Make sure to test and give feedback (it seems to be working fine now on my own tests though). Thanks!
