### ISSUE TITLE
Fractional columns within `#block`

### ISSUE THREAD

**Issue by maxcrees** [PgBiel/typst-tablex#44]
The upgrade to Typst 0.7.0 has revealed one regression and one longstanding issue.

Consider the following:

```
#table(columns: 1fr, [1A. table])
#tablex(columns: 1fr, [1B. tablex])

#block(table(columns: 1fr, [2A. table plain block]))
#block(tablex(columns: 1fr, [2B. tablex plain block]))

#block(breakable: true, table(columns: 1fr, [3A. table breakable: true]))
#block(breakable: true, tablex(columns: 1fr, [3B. tablex breakable: true]))

#block(breakable: false, table(columns: 1fr, [4A. table breakable: false]))
#block(breakable: false, tablex(columns: 1fr, [4B. tablex breakable: false]))
```

The behavior of these examples was unchanged from at least Typst 0.0.3 to 0.0.6 and tablex 0.0.2 to 0.0.4:

<img width="639" alt="image" src="https://github.com/PgBiel/typst-tablex/assets/118271/dbc806da-94c0-4937-ab1d-602ae9c24f8c">

Note how 2B and 3B are not drawn correctly.

<hr>

Then, in Typst 0.0.7 and tablex 0.0.4, example 4B changed (to become incorrect like 2B and 3B). Note that only 4B changed; all other examples appear identical to the above:

<img width="649" alt="image" src="https://github.com/PgBiel/typst-tablex/assets/118271/88ba1342-813f-42b9-aec0-43a2fca9d329">

**Comment by PgBiel** [comment]
Thanks for the detailed bug report. (This is likely related to #39)

I will investigate a solution as soon as I can.

**Comment by PgBiel** [comment]
Hi, I've pushed a fix to main with https://github.com/PgBiel/typst-tablex/commit/f00b91c7d9383ebd194fb9e36ee5999339c38891. Can you please test and see if everything is working properly now? Thanks!

**Comment by maxcrees** [comment]
Thanks for the quick response on this. The linked commit appears to fix 2B, 3B, and 4B. 
<img width="957" alt="image" src="https://github.com/PgBiel/typst-tablex/assets/118271/a16811a9-1f1a-4c60-a935-827b7da464cf">

**Comment by maxcrees** [comment]
This also fixes the problem in my original document. Well done!

**Comment by PgBiel** [comment]
Hooray! Thanks for the feedback! :smile:
