### ISSUE TITLE
[BUG] Table rotation is broken

### ISSUE THREAD

**Issue by giannissc** [PgBiel/typst-tablex#52]
When I use the default rotate function with tablex the layout is completely broken.

![Screenshot 2023-08-18 at 09-56-56 Design and Control of Fluidic Machines - main pdf](https://github.com/PgBiel/typst-tablex/assets/20277283/8aca9890-2a2b-4f5c-a552-43028adb866a)

EDIT:
Here is how it looks before the rotation:
![Screenshot 2023-08-18 at 09-57-54 Design and Control of Fluidic Machines - main pdf](https://github.com/PgBiel/typst-tablex/assets/20277283/4b83ae15-af6f-414a-ba89-1af5ada3816b)

The normal table function doesn't have this issue

**Comment by PgBiel** [comment]
Hello, I just tested locally and this seems to already have been fixed in the main branch (for 0.0.5, which should be released next week). You may want to give it a shot. Thanks!
