### ISSUE TITLE
Stroke parsing error in stroke-len()

### ISSUE THREAD

**Issue by igt-fred** [PgBiel/typst-tablex#55]
Hello and first thenk you for this very useful package.

Sorry for the title, I did not find a better one.
Just wanted to mention a small error on one of my table (nothing special really):
```
error: cannot access fields on type none
    ┌─ \tablex.typ:456:38
    │
456 │  s = repr(stroke).match(r).captures.first()
    │                            ^^^^^^^^
```

Nothing blocking, I just bypassed it with something like:
```
455  let r = regex("thickness: (\\d+(?:em|pt|cm|in|%))")
456  s = repr(stroke).match(r).captures.first()
-----
455  let r = regex("thickness: (\\d+(?:em|pt|cm|in|%))")
456  let xx = repr(stroke).match(r)
457  if xx != none { s = xx.captures.first() }
```
But as I am new to Typst, I prefer to let you fix it properly ;)
Hope it helps...

**Comment by PgBiel** [comment]
ah crap, I screwed up while fixing #49 lol

thanks for reporting! I'll release 0.0.6 soon with a hotfix (and perhaps other fixes if possible)

**Comment by PgBiel** [comment]
If you mind, can you please specify which stroke type you used? For testing

**Comment by igt-fred** [comment]
Sure, I simplified my example to the minimum throwing the error:
```
#let risks = ( (id: 1, desc: "Bla bla bla"), (id: 2, desc: "tutututu") )
#let riskContent = for risk in risks { ([#risk.id], [#risk.desc]) }
#tablex(columns: 2, align: (center, left), stroke: 0.4pt + black, inset: 4pt, ..riskContent)
```

**Comment by PgBiel** [comment]
Thank you!
