### ISSUE TITLE
Set kind of tablex to 'table', to get the supplement right if it is used inside a figure environment

### ISSUE THREAD

**Issue by JMNnl** [PgBiel/typst-tablex#57]
Hi, 
this is only a small issue: 
The kind() of a tablex()  is set to the figure type, but should be set to table to get the supplement correctly if it is used inside a figure environment to give it a caption and make it referenceable. 
Minimal example of the issue is given in the image below:

![grafik](https://github.com/PgBiel/typst-tablex/assets/64215841/655c6f9b-df77-478c-9608-44ebe73583a0)

Workaround: 
set the type inside the figure environment manually, see documentation for details https://typst.app/docs/reference/meta/figure/#parameters-kind  
```
#figure(
  kind: table,
  tablex()
)
```

**Comment by PgBiel** [comment]
Hi, see #7

This is a Typst thing and there isn't much we can do at the moment, unfortunately.
