### ISSUE TITLE
Compiler craps out with ref in table

### ISSUE THREAD

**Issue by KronosTheLate** [PgBiel/typst-tablex#8]
The following works:
![image](https://user-images.githubusercontent.com/61620837/235449491-e40a7682-351a-4885-b2f9-9d4b192165b9.png)

However, chaining the table to a tablex makes the compiler panic:
![image](https://user-images.githubusercontent.com/61620837/235449543-abc33ddf-43a0-4dbd-be30-e3f4be32ac98.png)

**Comment by PgBiel** [comment]
This seems like a compiler bug, but I think this is fixed in Typst v0.3.0 (see https://github.com/typst/typst/pull/811). As you're using VSCode, I assume you're using Typst LSP, which uses Typst v0.2.0. Can you please try running your code in the web app to check if it still does that? Thank you.

**Comment by PgBiel** [comment]
Worth saying that, even with the compiler crash being fixed, what you're trying to do won't work, because references/cites are broken inside `locate` objects (and tablex uses locate) - see https://github.com/typst/typst/issues/785. This is a Typst limitation and currently has no (practical) workaround, but let's keep an eye on that.

**Comment by KronosTheLate** [comment]
> This seems like a compiler bug, but I think this is fixed in Typst v0.3.0 (see [typst/typst#811](https://github.com/typst/typst/pull/811)). As you're using VSCode, I assume you're using Typst LSP, which still uses Typst v0.2.0. Can you please try running your code in the web app (which has Typst v0.3.0) to check if it still does that? Thank you.

I did indeed use 2.0 for that. I have upgraded now, but I will not retry, as you said it would not work either way.

I would love to see your tables become the default for typst. The merging behavior was really intuitive in my limited use.

**Comment by PgBiel** [comment]
This bug has been fixed in Typst v0.6.0. From that compiler version onwards, you can now use citations and references from within Tablex tables! Yay! :tada:
