### ISSUE TITLE
Bug with using measure and lines inside a table

### ISSUE THREAD

**Issue by johannes-wolf** [PgBiel/typst-tablex#80]
The following code returns a size of `(0pt, 0pt)`, while measuring other elements like `rect` or `box` works.

```typst
#tablex(
  style(st => {
    measure(line(length: 1cm), st)
  })
)
```

This error occurs when trying to use cetz canvas (0.1.2) insides tablex, see https://github.com/johannes-wolf/cetz/issues/345.

**Comment by PgBiel** [comment]
This was actually a huge oversight by my part, and broke not only measuring lines but also, really, placing any lines inside the table, as I was using `#show line: place.with(top + left, dy: some-constant-here)`. Thanks for reporting!
