### ISSUE TITLE
`align:` function arguments are the other way around

### ISSUE THREAD

**Issue by rmolinari** [PgBiel/typst-tablex#9]
The roadmap mentions that the `align:` argument can take a function:
> Accept a function ((row, column) => alignment/2d alignment)

My experimentation shows that the arguments are actually `(column, row)`, not `(row, column)`.

**Comment by PgBiel** [comment]
Fixed in https://github.com/PgBiel/typst-tablex/commit/32823fea0189461a1662e8a169cce1310afac604, thanks!
